
export const metadata = {
  title: "Jelajah",
  description: "Generated by create next app",
};

export default function AuthLAyout({ children }) {
  return (
    <>
      <section class="section">
        <div class="container mt-5">
          <div class="row">{children}</div>
        </div>
      </section>
    </>
  );
}
