import { StoreProvider } from "@/redux/StoreProvider";
import Head from "next/head";

export const metadata = {
  title: "Jelajah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
      <Head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      </Head>
      <body
      // className={inter.className}
      >
        {children}
      </body>

    </html>
    </StoreProvider>
  );
}
